"""empty message

Revision ID: fc08e0f35699
Revises: 57c87c41c9fe
Create Date: 2024-04-13 19:17:00.207327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc08e0f35699'
down_revision: Union[str, None] = '57c87c41c9fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'storedata', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storedata', type_='unique')
    # ### end Alembic commands ###
